# Copyright (c) 2021, Teslabs Engineering S.L.
# SPDX-License-Identifier: Apache-2.0

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: teslabs/spinner:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: spinner

      - name: Cache Zephyr
        uses: actions/cache@v3
        with:
          path: |
            modules
            zephyr
          key: ${{ hashFiles('spinner/west.yml') }}

      - name: Initialize
        working-directory: spinner
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt
          pip3 install -r ../zephyr/scripts/requirements-build-test.txt
          pip3 install -r ../zephyr/scripts/requirements-run-test.txt
          pip3 install -r docs/requirements.txt

      - name: Lint code
        run: |
          git diff --name-only ${{ github.base_ref}} ${{ github.sha }} -- '*.[ch]' | xargs zephyr/scripts/checkpatch.pl

      - name: Build
        working-directory: spinner
        run: |
          west build -b nucleo_f302r8 spinner -p -- -DSHIELD=ihm07m1
          west build -b nucleo_f302r8 spinner -p -- -DSHIELD=ihm16m1
          west build -b nucleo_g431rb spinner -p -- -DSHIELD=ihm07m1
          west build -b nucleo_g431rb spinner -p -- -DSHIELD=ihm16m1

      - name: Test
        working-directory: spinner
        run: |
          west twister -T tests --integration -v
